/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dane {
	char przesylaneDane[1024];
	char nazwaPliku[30];
	int wielkoscPliku;
	int licznik;
};
typedef struct dane dane;

struct pobranieNazwy {
	char nazwaPliku[30];
};
typedef struct pobranieNazwy pobranieNazwy;

struct daneKontrolne {
	char nazwaPliku[30];
	int polozenie;
};
typedef struct daneKontrolne daneKontrolne;

#define FTP 0x30000004
#define FTP_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define wysylaniePliku 1
extern  int * wysylaniepliku_1(dane *, CLIENT *);
extern  int * wysylaniepliku_1_svc(dane *, struct svc_req *);
#define rozmiarPliku 2
extern  int * rozmiarpliku_1(pobranieNazwy *, CLIENT *);
extern  int * rozmiarpliku_1_svc(pobranieNazwy *, struct svc_req *);
#define czyPlikIstnieje 3
extern  int * czyplikistnieje_1(pobranieNazwy *, CLIENT *);
extern  int * czyplikistnieje_1_svc(pobranieNazwy *, struct svc_req *);
#define pobieraniePliku 4
extern  dane * pobieraniepliku_1(daneKontrolne *, CLIENT *);
extern  dane * pobieraniepliku_1_svc(daneKontrolne *, struct svc_req *);
extern int ftp_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define wysylaniePliku 1
extern  int * wysylaniepliku_1();
extern  int * wysylaniepliku_1_svc();
#define rozmiarPliku 2
extern  int * rozmiarpliku_1();
extern  int * rozmiarpliku_1_svc();
#define czyPlikIstnieje 3
extern  int * czyplikistnieje_1();
extern  int * czyplikistnieje_1_svc();
#define pobieraniePliku 4
extern  dane * pobieraniepliku_1();
extern  dane * pobieraniepliku_1_svc();
extern int ftp_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dane (XDR *, dane*);
extern  bool_t xdr_pobranieNazwy (XDR *, pobranieNazwy*);
extern  bool_t xdr_daneKontrolne (XDR *, daneKontrolne*);

#else /* K&R C */
extern bool_t xdr_dane ();
extern bool_t xdr_pobranieNazwy ();
extern bool_t xdr_daneKontrolne ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
