/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
ftp_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		dane wysylaniepliku_1_arg;
		pobranieNazwy rozmiarpliku_1_arg;
		pobranieNazwy czyplikistnieje_1_arg;
		daneKontrolne pobieraniepliku_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case wysylaniePliku:
		_xdr_argument = (xdrproc_t) xdr_dane;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) wysylaniepliku_1_svc;
		break;

	case rozmiarPliku:
		_xdr_argument = (xdrproc_t) xdr_pobranieNazwy;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rozmiarpliku_1_svc;
		break;

	case czyPlikIstnieje:
		_xdr_argument = (xdrproc_t) xdr_pobranieNazwy;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) czyplikistnieje_1_svc;
		break;

	case pobieraniePliku:
		_xdr_argument = (xdrproc_t) xdr_daneKontrolne;
		_xdr_result = (xdrproc_t) xdr_dane;
		local = (char *(*)(char *, struct svc_req *)) pobieraniepliku_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (FTP, FTP_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FTP, FTP_VER, ftp_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FTP, FTP_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FTP, FTP_VER, ftp_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FTP, FTP_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
