/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"

bool_t
xdr_dane (XDR *xdrs, dane *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->przesylaneDane, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nazwaPliku, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->wielkoscPliku))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->licznik))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pobranieNazwy (XDR *xdrs, pobranieNazwy *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nazwaPliku, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_daneKontrolne (XDR *xdrs, daneKontrolne *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nazwaPliku, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->polozenie))
		 return FALSE;
	return TRUE;
}
