/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftp.h"
#include <stdio.h>
#include <stdlib.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xos.h>
#include <X11/Xatom.h>

void
ftp_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	dane  wysylaniepliku_1_arg;
	int  *result_2;
	pobranieNazwy  rozmiarpliku_1_arg;
	int  *result_3;
	pobranieNazwy  czyplikistnieje_1_arg;
	dane  *result_4;
	daneKontrolne  pobieraniepliku_1_arg;

#ifndef	DEBUG

	// Uwtorzenie klienta i deklaracja korzystania z protokolu UDP
	clnt = clnt_create (host, FTP, FTP_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// Zmienne do utworzenia i aktywacji okien
	Display *dpy;
	int screen;
	Window win;
	Window przycisk1;
	Window przycisk2;
	Window wprowadzanieTesktu;
	Window zakonczProgram;
	Window naglowek;
	XEvent event;
	int aktywnePisanie = 0;
	int wysylanie = 0;
	int pobieranie = 0;

	// Zmienne do obslugi tekstu
	GC gc;
	KeySym key;	
	char text[30];
	char napis[30];
	char ch;
	memset(napis, 0, 30); 

	// Zmienne do ustawienia geometrii
	int przycisk1_x, przycisk1_y, przycisk1_width, przycisk1_height, przycisk1_border_width, przycisk1_depth;
	int przycisk2_x, przycisk2_y, przycisk2_width, przycisk2_height, przycisk2_border_width, przycisk2_depth;
	Window root_win;
	
	// Zmienne do ustawienia kolorow
	Colormap colormap;
	XColor przycisk1_color, przycisk2_color, przyciskZamknij_color;
	XColor jasnoszary_color, ciemnoszary_color;
	XGCValues gcv_jasnoszary, gcv_ciemnoszary;
	GC gc_jasnoszary, gc_ciemnoszary;

	dpy = XOpenDisplay(NULL);

	// Sprawdzenie czy udalo sie utworzyc glowne okno
	if(dpy == NULL){
		fprintf(stderr, "Nie udalo sie otworzyc okna\n");
	}

	screen = DefaultScreen(dpy);

	// Konfiguracja glownego okna
	win = XCreateSimpleWindow(dpy, RootWindow(dpy, screen),
		100, 100, 500, 400,
		1, BlackPixel(dpy, screen), WhitePixel(dpy, screen));

	XSelectInput(dpy, win, ExposureMask | KeyPressMask);
	XMapWindow(dpy, win);

	// Ustawienie nazwy aplikacji
	XSetStandardProperties(dpy,win,"KLIENT FTP","FTP",None,NULL,0,NULL);

	

	// --- Przycisk wgrywania ---
	// Ustawienie koloru wnetrza - niebieski
	colormap = DefaultColormap(dpy, screen);
	XParseColor(dpy, colormap, "rgb:7a/db/fa", &przycisk1_color);
	XAllocColor(dpy, colormap, &przycisk1_color);

	// Ustawienie koloru ramek - szary
	XParseColor(dpy, colormap, "rgb:ee/ee/ee", &jasnoszary_color);
	XAllocColor(dpy, colormap, &jasnoszary_color);
	gcv_jasnoszary.foreground = jasnoszary_color.pixel;
	gcv_jasnoszary.background = przycisk1_color.pixel;
	gc_jasnoszary = XCreateGC(dpy, RootWindow(dpy, screen),
		GCForeground | GCBackground, &gcv_jasnoszary);

	XParseColor(dpy, colormap, "rgb:88/88/88", &ciemnoszary_color);
	XAllocColor(dpy, colormap, &ciemnoszary_color);
	gcv_ciemnoszary.foreground = ciemnoszary_color.pixel;
	gcv_ciemnoszary.background = przycisk1_color.pixel;
	gc_ciemnoszary = XCreateGC(dpy, RootWindow(dpy, screen),
		GCForeground | GCBackground, &gcv_ciemnoszary);

	// Konfiguracja przycisku wgrywania
	przycisk1 = XCreateSimpleWindow(dpy, win,
		30, 40, 200, 100,
		1, BlackPixel(dpy, screen), przycisk1_color.pixel);
	XSelectInput(dpy, przycisk1, ExposureMask | KeyPressMask | ButtonPressMask | ButtonReleaseMask);
	XMapWindow(dpy, przycisk1);
	XGetGeometry(dpy, przycisk1, &root_win, &przycisk1_x, &przycisk1_y, &przycisk1_width, &przycisk1_height,
		&przycisk1_border_width, &przycisk1_depth);



	// --- Przycisk pobierania ---
	// Ustawienie koloru wnetrza - zielony
	colormap = DefaultColormap(dpy, screen);
	XParseColor(dpy, colormap, "rgb:7a/db/78", &przycisk2_color);
	XAllocColor(dpy, colormap, &przycisk2_color);

	// Ustawienie koloru ramek - szary
	XParseColor(dpy, colormap, "rgb:ee/ee/ee", &jasnoszary_color);
	XAllocColor(dpy, colormap, &jasnoszary_color);
	gcv_jasnoszary.foreground = jasnoszary_color.pixel;
	gcv_jasnoszary.background = przycisk2_color.pixel;
	gc_jasnoszary = XCreateGC(dpy, RootWindow(dpy, screen),
		GCForeground | GCBackground, &gcv_jasnoszary);

	XParseColor(dpy, colormap, "rgb:88/88/88", &ciemnoszary_color);
	XAllocColor(dpy, colormap, &ciemnoszary_color);
	gcv_ciemnoszary.foreground = ciemnoszary_color.pixel;
	gcv_ciemnoszary.background = przycisk2_color.pixel;
	gc_ciemnoszary = XCreateGC(dpy, RootWindow(dpy, screen),
		GCForeground | GCBackground, &gcv_ciemnoszary);

	// Konfiguracja przycisku pobierania
	przycisk2 = XCreateSimpleWindow(dpy, win,
		250, 40, 200, 100,
		1, BlackPixel(dpy, screen), przycisk2_color.pixel);
	XSelectInput(dpy, przycisk2, ExposureMask | KeyPressMask | ButtonPressMask | ButtonReleaseMask);
	XMapWindow(dpy, przycisk2);
	XGetGeometry(dpy, przycisk2, &root_win, &przycisk2_x, &przycisk2_y, &przycisk2_width, &przycisk2_height,
		&przycisk2_border_width, &przycisk2_depth);



	// Konfiguracja naglowka aplikacji
	naglowek = XCreateSimpleWindow(dpy, win,
		185, 10, 200, 30,
		0, BlackPixel(dpy, screen), WhitePixel(dpy, screen));
	XSelectInput(dpy, naglowek, ExposureMask | KeyPress);
	XMapWindow(dpy, naglowek);



	// Konfiguracja okna wprowadzania tekstu
	wprowadzanieTesktu = XCreateSimpleWindow(dpy, win,
		150, 210, 200, 50,
		2, BlackPixel(dpy, screen), WhitePixel(dpy, screen));
	XSelectInput(dpy, wprowadzanieTesktu, ExposureMask | KeyPress);
	XMapWindow(dpy, wprowadzanieTesktu);



	// --- Przycisk zamkniecia programu ---
	// Ustawienie koloru - czerwony
	colormap = DefaultColormap(dpy, screen);
	XParseColor(dpy, colormap, "rgb:ff/99/99", &przyciskZamknij_color);
	XAllocColor(dpy, colormap, &przyciskZamknij_color);

	zakonczProgram = XCreateSimpleWindow(dpy, win, 180, 300, 150, 60,
		1, BlackPixel(dpy, screen), przyciskZamknij_color.pixel);

	XSelectInput(dpy, zakonczProgram, ExposureMask | KeyPress | ButtonPressMask | ButtonReleaseMask);
	XMapWindow(dpy, zakonczProgram);

	gc=XCreateGC(dpy, win, 0,0);

	while(1){

		// Pobranie zdarzenia
		XNextEvent(dpy, &event);

		// Wypisanie naglowka
		if(event.type == Expose){
			XDrawString(dpy,naglowek,gc,10,10, "WYBIERZ OPERACJE", 16);
		}

		// Obsluga zdarzen przycisku wysylania
		if(event.xany.window == przycisk1){

			// Ustawienie ramki przycisku
			if(event.type == Expose){
				XDrawLine(dpy, przycisk1, gc_jasnoszary,
						0,0,przycisk1_width-1, 0);
				XDrawLine(dpy, przycisk1, gc_jasnoszary,
						0,0,0, przycisk1_height-1);
				XDrawLine(dpy, przycisk1, gc_ciemnoszary,
						przycisk1_width-1,0,przycisk1_width-1,przycisk1_height-1);
				XDrawLine(dpy, przycisk1, gc_ciemnoszary,
						0,przycisk1_height-1,przycisk1_width-1,przycisk1_height-1);	

				// Dodanie napisu na przycisku
				XDrawString(dpy,przycisk1,gc,70,50, "WYSYLANIE", 9);
			}

			// Obluga zdarzenia nacisniecia przycisku
			if(event.type == ButtonPress){
				if(event.xbutton.button == 1){
					XDrawLine(dpy, przycisk1, gc_ciemnoszary,
						0,0,przycisk1_width-1, 0);
					XDrawLine(dpy, przycisk1, gc_ciemnoszary,
							0,0,0, przycisk1_height-1);
					XDrawLine(dpy, przycisk1, gc_jasnoszary,
							przycisk1_width-1,0,przycisk1_width-1,przycisk1_height-1);
					XDrawLine(dpy, przycisk1, gc_jasnoszary,
							0,przycisk1_height-1,przycisk1_width-1,przycisk1_height-1);

					//wyczyszczenie okna
					XClearWindow(dpy, win);
				}
			}

			// Obsluga zdarzenia puszczenia przycisku
			if(event.type == ButtonRelease){
				if(event.xbutton.button == 1){
					XDrawLine(dpy, przycisk1, gc_jasnoszary,
							0,0,przycisk1_width-1, 0);
					XDrawLine(dpy, przycisk1, gc_jasnoszary,
							0,0,0, przycisk1_height-1);
					XDrawLine(dpy, przycisk1, gc_ciemnoszary,
							przycisk1_width-1,0,przycisk1_width-1,przycisk1_height-1);
					XDrawLine(dpy, przycisk1, gc_ciemnoszary,
							0,przycisk1_height-1,przycisk1_width-1,przycisk1_height-1);	

					// Aktywowanie mozliwosci wprowadzania tekstu i funkcji wysylania pliku
					aktywnePisanie = 1;
					wysylanie = 1;
					XDrawString(dpy,win,gc,140,170, "Wprowadz nazwe pliku i wcisnij spacje", 37);
				}
			}
		}

		// Obsluga zdarzen przycisku pobierania
		if(event.xany.window == przycisk2){

			// Ustawienie ramki przycisku
			if(event.type == Expose){
				XDrawLine(dpy, przycisk2, gc_jasnoszary,
						0,0,przycisk2_width-1, 0);
				XDrawLine(dpy, przycisk2, gc_jasnoszary,
						0,0,0, przycisk2_height-1);
				XDrawLine(dpy, przycisk2, gc_ciemnoszary,
						przycisk2_width-1,0,przycisk2_width-1,przycisk2_height-1);
				XDrawLine(dpy, przycisk2, gc_ciemnoszary,
						0,przycisk2_height-1,przycisk2_width-1,przycisk2_height-1);	

				XDrawString(dpy,przycisk2,gc,70,50, "POBIERANIE", 10);	
			}

			// Obluga zdarzenia nacisniecia przycisku
			if(event.type == ButtonPress){
				if(event.xbutton.button == 1){
					XDrawLine(dpy, przycisk2, gc_ciemnoszary,
						0,0,przycisk2_width-1, 0);
					XDrawLine(dpy, przycisk2, gc_ciemnoszary,
							0,0,0, przycisk2_height-1);
					XDrawLine(dpy, przycisk2, gc_jasnoszary,
							przycisk2_width-1,0,przycisk2_width-1,przycisk2_height-1);
					XDrawLine(dpy, przycisk2, gc_jasnoszary,
							0,przycisk2_height-1,przycisk2_width-1,przycisk2_height-1);

					//Wyczyszczenie okna
					XClearWindow(dpy, win);
				}
			}

			// Obsluga zdarzenia puszczenia przycisku
			if(event.type == ButtonRelease){
				if(event.xbutton.button == 1){
					XDrawLine(dpy, przycisk2, gc_jasnoszary,
							0,0,przycisk2_width-1, 0);
					XDrawLine(dpy, przycisk2, gc_jasnoszary,
							0,0,0, przycisk2_height-1);
					XDrawLine(dpy, przycisk2, gc_ciemnoszary,
							przycisk2_width-1,0,przycisk2_width-1,przycisk2_height-1);
					XDrawLine(dpy, przycisk2, gc_ciemnoszary,
							0,przycisk2_height-1,przycisk2_width-1,przycisk2_height-1);

					// Aktywowanie mozliwosci wprowadzania tekstu i funkcji pobierania pliku
					aktywnePisanie = 1;
					pobieranie = 1;
					memset(napis, 0, 30);
					XDrawString(dpy,win,gc,140,170, "Wprowadz nazwe pliku i wcisnij spacje", 37);
				}
			}
		}

		// Obsluga zdarzenia wprowadzania tesktu oraz wysylania pliku
		if (event.type==KeyPress&&
		    XLookupString(&event.xkey,text,30,&key,0) == 1 && aktywnePisanie==1 && wysylanie==1){
		    	
		    	// Przypisanie do zmiennej wcisnietego przycisku
		    	ch = text[0];

		    	// Sprawdzenie czy wcisnieto spacje - koniec wprowadzania tekstu
				if (text[0]==' '){

					// Wylaczenie mozliwosci wpisywania tekstu
					aktywnePisanie = 0;

					// Utworzenie zmiennych do obslugi wysylania
					char bufor[1024];
				    char nazwaPliku[30];
				    int wielkoscPliku;

				    // Wyczyszczenie buforow
				    memset(bufor, 0, 1024);
				    memset(nazwaPliku, 0, 1024);
				    wielkoscPliku = 0;
				
					// Przypisanie wprowadzonego tekstu do nazwy pliku
				    strcpy(nazwaPliku, napis);
				    
				    // Otworzenie pliku w trybie odczytu binarnego
				    FILE *fplik = fopen(nazwaPliku, "rb");

				    // Sprawdzenie czy plik istnieje
				    if( !fplik )
				    {
						XDrawString(dpy,win,gc,180,190, "Podany plik nie istnieje", 24);
						memset(napis, 0, 30);
						wysylanie = 0;
						XClearWindow(dpy, wprowadzanieTesktu);
						continue;
				    }


				    // Obiczenie rozmiaru pliku
				    fseek(fplik, 0, SEEK_END);
				    wielkoscPliku = ftell(fplik);
				    fseek(fplik, 0, SEEK_SET);

				    // Wczytanie pierwszej porcji informacji z pliku
					fread(bufor, 1024,1,fplik);

				    int licznik =1;
				    int licznik2 = 0;

				    // Przesylanie pliku w fragmentach ze wzgledu na ograniczenia protokolu UDP
				    while(licznik*1024<wielkoscPliku){  	
				        strcpy(wysylaniepliku_1_arg.przesylaneDane, bufor);
				    	strcpy(wysylaniepliku_1_arg.nazwaPliku,nazwaPliku);
				    	wysylaniepliku_1_arg.wielkoscPliku = wielkoscPliku;
				    	wysylaniepliku_1_arg.licznik = licznik2;
				    	result_1 = wysylaniepliku_1(&wysylaniepliku_1_arg, clnt);

				        memset(bufor,0,1024);
				        fread(bufor, 1024,1,fplik);
				        licznik++;
				        licznik2++;
				        
				    }

				    // Wczytanie ostatniej czesci pliku
				    fread(bufor, (wielkoscPliku % 1024), 1, fplik);
		    		strcpy(wysylaniepliku_1_arg.przesylaneDane, bufor);
				    strcpy(wysylaniepliku_1_arg.nazwaPliku,nazwaPliku);
				    wysylaniepliku_1_arg.licznik = licznik2;
				    wysylaniepliku_1_arg.wielkoscPliku = wielkoscPliku;
				    result_1 = wysylaniepliku_1(&wysylaniepliku_1_arg, clnt);

				    // Zamkniecie pliku
				    fclose(fplik);				    
				 
				    // Wyswietlenie informacji o pomyslnym wyslaniu pliku
				    XDrawString(dpy,win,gc,190,190, "Plik zostal wyslany", 19);

				    // Wyczyszczenie okna i zwolnienie pamieci
				    XClearWindow(dpy, wprowadzanieTesktu);
				    memset(napis, 0, 30);

				    // Wylaczenie funkcji wysylania pliku
				    wysylanie = 0;
				}

			// Dolaczenie wcisnietego klawisza do napisu
			strncat(napis, &ch, 1);

			// Wyswietelenie aktualnie wprowadzonego tekstu
			XDrawString(dpy,wprowadzanieTesktu,gc,20,25, napis, strlen(napis));
		} 

		// Obsluga zdarzenia wprowadzania tesktu oraz pobierania pliku pliku
		if (event.type==KeyPress&&
		    XLookupString(&event.xkey,text,30,&key,0) == 1 && aktywnePisanie==1 && pobieranie==1){
		    	
				// Przypisanie do zmiennej wcisnietego przycisku
		    	ch = text[0];

		    	// Sprawdzenie czy wcisnieto spacje - koniec wprowadzania tekstu
				if (text[0]==' '){
					
					// Wylaczenie mozliwosci wprowadzania tekstu
					aktywnePisanie = 0;

					
					// Utworzenie zmiennych do obslugi pobierania
				    char bufor[1024];
				    char nazwaPliku[30];

				    // Wyczyszczenie buforow
				    memset(bufor, 0, 1024);
				    memset(nazwaPliku, 0, 30);

				    // Przypisanie wprowadzonego tekstu do nazwy pliku
				    strcpy(nazwaPliku, napis);

				    // Sprawdzenie czy jest taki plik na serwerze
				    strcpy(czyplikistnieje_1_arg.nazwaPliku, nazwaPliku);
				    result_3 = czyplikistnieje_1(&czyplikistnieje_1_arg, clnt);

				    // Funckja zwraca 1 jesli plik znajduje sie na serwerze
				    if(*result_3 == 1){

				    	// Zmienna przechowujaca rozmiar pliku
						int rozmiar = 0;

						// Pobranie rozmiaru pliku
						strcpy(rozmiarpliku_1_arg.nazwaPliku, nazwaPliku);
						result_2 = rozmiarpliku_1(&rozmiarpliku_1_arg, clnt);

						int licznik = 1;

						// Pobieranie pliku w fragemtach ze wzgledu na ograniczenia protokolu UDP 
				        while(licznik*1024<*result_2){

				        	// Sprawdzenie jaka czesc pliku zostala juz pobrana
							FILE *f = fopen(nazwaPliku, "rb"); 
							if(f){
							    fseek(f, 0, SEEK_END);
							    rozmiar = ftell(f);
							    fseek(f, 0, SEEK_SET);
							    fclose(f);
							}

							// Otwarcie pliku w trybie binarnym umozliwajacym dodawanie kolejnych danych 
					        FILE *fplik = fopen(nazwaPliku, "ab");
					        
					        // Przeslanie inforamcji ile juz zostalo pobrane i odebranie kolejnej czesci danych
					        strcpy(pobieraniepliku_1_arg.nazwaPliku, nazwaPliku);
							pobieraniepliku_1_arg.polozenie = rozmiar;
							result_4 = pobieraniepliku_1(&pobieraniepliku_1_arg, clnt);			
							strcpy(bufor,result_4->przesylaneDane);

					        fwrite(bufor, 1024, 1, fplik);
					        memset(bufor,0,1024);
					        fclose(fplik);
					        licznik++;
				        }

				        // Pobranie ostatniej czesci pliku
				        FILE *f = fopen(nazwaPliku, "rb"); 
						if(f){
						    fseek(f, 0, SEEK_END);
						    rozmiar = ftell(f);
						    fseek(f, 0, SEEK_SET);
						    fclose(f);
						}

				        FILE *fplik = fopen(nazwaPliku, "ab");
				        strcpy(pobieraniepliku_1_arg.nazwaPliku, nazwaPliku);
						pobieraniepliku_1_arg.polozenie = rozmiar;
						result_4 = pobieraniepliku_1(&pobieraniepliku_1_arg, clnt);
								
						strcpy(bufor,result_4->przesylaneDane);
				        fwrite(bufor, (*result_2)%1024, 1, fplik);
				        memset(bufor,0,1024);
				        fclose(fplik);

						// Wyswietlenie informacji o pomyslnym pobraniu pliku
				        XDrawString(dpy,win,gc,190,190, "Plik zostal pobrany", 19);

					    // Wyczyszczenie okna i zwolnienie pamieci
					    XClearWindow(dpy, wprowadzanieTesktu);
					    memset(napis, 0, 30);

					    // Wylaczenie funkcji pobierania pliku
					    pobieranie = 0;
				    } else {

				    	// Wylaczenie mozliwosci wprowadzania tekstu
				    	aktywnePisanie = 0;

				    	// Wyswietlenie informacji o braku pliku na serwerze
				    	XDrawString(dpy,win,gc,185,190, "Pliku nie ma na serwerze", 24);

					    // Wyczyszczenie okna i zwolnienie pamieci
					    XClearWindow(dpy, wprowadzanieTesktu);
					    memset(napis, 0, 30);

					    // Wylaczenie funkcji pobierania pliku
					    pobieranie = 0;
				    }	
				}

			// Dolaczenie wcisnietego klawisza do napisu
			strncat(napis, &ch, 1);

			// Wyswietelenie aktualnie wprowadzonego tekstu
			XDrawString(dpy,wprowadzanieTesktu,gc,20,25, napis, strlen(napis));

		}

		// Obsluga zdarzenie zakonczenia programu
		if(event.xany.window == zakonczProgram){

			// Wyswietlenie tekstu w przycisku
			if(event.type == Expose){
				XDrawString(dpy,zakonczProgram,gc,55,35, "Zakoncz", 7);
			}

			// Obsluga zdarzenia puszczenia przycisku
			if(event.type == ButtonRelease){
				if(event.xbutton.button == 1){

					// Zwolnienie pamieci i zamkniecie programu
					XFreeGC(dpy, gc);
					XDestroyWindow(dpy,win);
					XCloseDisplay(dpy);	
					exit(1);
				}
			}
		}
	}


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	//Sprawdzenie czy podano adres serwera jako parametr
	if (argc < 2) {
		printf ("Wpisz: %s adres serwera\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ftp_1 (host);
	exit (0);
}